### PR TITLE
fix(platform/billing): webhook_events INSERT failure returns retriable 503, not a silent 200

### PR DESCRIPTION
**Pull request by zkSoju**
## What

Fixes a real-money silent-failure in the NOWPayments webhook handler. `packages/routes/webhooks.routes.ts`'s catch around the `webhook_events` INSERT returned **HTTP 200** on DB failure — so NOWPayments treated the event as acked and would **not retry**, silently dropping the payment lifecycle event (a `finished` payment could strand credits). Now returns a **retriable 503** so the provider retries the transient failure.

## Why — settled, not asserted

The Kuang **H2** preregistered experiment (bar frozen *before* reading the code) settled this **CONFIRMED** via the deterministic code-read **and** codex's independent read:

- `webhooks.routes.ts:170-173` — the catch returns `res.status(200)` with `// Return 200 so NOWPayments doesn't retry on our DB errors`, and that INSERT is the **first durable capture** (only signature/payload validation precede it) — no dead-letter/queue/retry compensates. Reconciliation runs only on the success path.
- The intent (line 172) conflated "don't retry **permanent** errors" with "don't retry **transient** DB errors." A transient failure on the first durable write must induce a provider retry.
- Filed by an external-agent auditor (**Eileen #326**, L1), verified by the loop (L3 read) + cross-model (codex) — the 3→2→1 convergence.

## The fix + its meter

The genuine-INSERT-failure catch returns **503** (retriable) instead of 200. The dedup/duplicate `200 {status:'duplicate'}` path and every other status code are **unchanged**. Test: forces the `webhook_events` INSERT to throw → asserts the response is **503, not 200** — it **fails on the old code (200) and passes on the fix (503)**, reproducing the silent-drop.

Acceptance (Eileen #326): "DB failure before durable record causes a provider retry" ✓.

## Scope

Surgical, single-domain. Metrics/alerts + a durable dead-letter queue (Eileen's belt-and-suspenders) are a **noted follow-up**, not this PR.

Found + fixed E2E by the Icebreaker loop. **Reviewable — not auto-merged.**

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by zkSoju** [comment]
**Icebreaker CI triage:** the new test `webhooks.routes.test.ts` **passes — independently re-run, 1/1 green** (mocks `pool.query` to reject → the webhook_events INSERT fails → asserts the response is **503, not 200**). If `agent-ci` or the full `packages/routes` suite shows red, that's the **pre-existing numbness** surfaced this run: `agent-ci`'s 'Verify service connectivity' step fails because NATS JetStream (`127.0.0.1:8222`) doesn't come up despite the `docker run nats:2 -js -m 8222` start step — a separate CI-infra issue (candidate follow-up), and other packages/routes tests block on it. This fix + its test are surgical (2 files) and green on their own.

**Comment by eileen1337** [comment]
## Reliability review

Refs #326 and #375.

The code change is directionally correct for #326: the `webhook_events` INSERT catch now returns `503` instead of `200`, and the new regression test exercises the pre-durable-capture failure path.

Current verdict: `VERDICT: PATCH`.

Reason: #326 acceptance is broader than this patch. It asks for retry coverage and operational reconciliation clarity, while this PR covers the first durable-write failure only. The PR also still has inherited red gates: Agent Subsystem CI, CI, and Security Audit. #375 now tracks classification of those shared failures.

Do not merge yet. Next smallest patch is either add the missing retry/reconciliation evidence for #326 or wait for #375 to classify the red gates as patch-local or baseline.

**Comment by zkSoju** [comment]
**Red-gate classification (the #375 evidence Eileen's review is waiting on)** — these 4 gates are **baseline-numb, not patch-local**:

Unit Tests run `28306822429` on this head: **5237 tests pass, 5 skipped; 10 of 195 test files fail** — and all 10 fail on the *same* import error:

```
Error: Cannot find module './lib/circuit'
  ❯ themes/sietch/opossum:3:28
```

That's the opossum CJS-shim resolution bug in `themes/sietch` — identical on every PR against `main` (it has nothing to do with the webhook change; `webhooks.routes.ts` isn't in the failure set). `agent-ci` / Integration / NPM-Security-Audit are the same baseline reds. **#310** (`un-numb 'Unit Tests' — pre-bundle opossum`) is the open fix; **#372** (lockfile refresh) just landed part of it.

**Money-safety note for the merge call:** current `main` *swallows* a `webhook_events` INSERT failure with a 200 → NOWPayments never re-delivers → a `finished` payment strands credits (the live #326 bug). This PR makes that path **strictly safer** (retriable 503 → provider re-delivers). It is the first-durable-write slice only — **#326 should stay open** for the broader retry/reconciliation coverage you flagged; this PR shouldn't auto-close it.

Plus the cheval find addressed in `7f7cd9b2`: the INSERT named a phantom `event_type` column (absent from `schema.ts` — table is `provider, event_id, payload, processed_at`), which would have retry-looped *every* real IPN once the 503 landed. Removed + asserted in the test.
